/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define VS_TEMPL_VERSION "0.4.8"

#define VS_TEMPL_VERSION_MAJOR 0

#define VS_TEMPL_VERSION_MINOR 4

#define VS_TEMPL_VERSION_REV 8

