name: Building & Testing
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-build
  cancel-in-progress: true

on:
  workflow_call:
  push:
    branches: [master]
    paths:
      - "**"
      - "!**.md"

  pull_request:
    branches: [master]
    paths:
      - "**"
      - "!**.md"

jobs:
  linux-amd64:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install meson ninja
      - name: Configure and build
        run: |
          meson setup build/
          meson compile -C build/ 
          #meson test -C build/ --suite=vs-templ #Silence them for now since they are not completed yet
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-meson-logs
          path: |
            build/meson-logs/**/*
